######################################################################
# Automatically generated by qmake (2.01a) ??? ??? 13 16:06:51 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += LoginWindow.hpp RegistrationWindow.hpp ../core/InputValidator.hpp
SOURCES += LoginWindow.cpp Main.cpp RegistrationWindow.cpp
