######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 13 16:03:29 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Avatar.hpp mainWindow.hpp mainWindow.cpp
SOURCES += Avatar.cpp main.cpp mainWindow.cpp
