######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 7 14:37:46 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += registration.h registration.hpp registration.cpp
SOURCES += main.cpp registration.cpp
